export enum ActionType {
  // User actions
  USER_LOADING = 'USER_LOADING',
  USER_LOADED = 'USER_LOADED',
  USER_ERROR = 'USER_ERROR',

  // Auth actions
  AUTH_LOADING = 'AUTH_LOADING',
  AUTH_LOADED = 'AUTH_LOADED',
  AUTH_ERROR = 'AUTH_ERROR',
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  LOGIN_FAIL = 'LOGIN_FAIL',
  LOGOUT = 'LOGOUT',

  REGISTER_SUCCESS = 'REGISTER_SUCCESS',
  REGISTER_FAIL = 'REGISTER_FAIL', 
  

}

